#!/usr/bin/env bash

# From https://wiki.archlinux.org/title/NFS#Automatic_mount_handling

function net_umount {
  umount -l -f $1 &>/dev/null
}

function net_mount {
  mountpoint -q $1 || mount $1
}

NET_MOUNTS=$(sed -e '/^.*#/d' -e '/^.*:/!d' -e 's/\t/ /g' /etc/fstab | tr -s " ")
[ -z "$NET_MOUNTS" ] && exit 0

NET_MOUNTS=${NET_MOUNTS}$'\n'b

printf %s "$NET_MOUNTS" | while IFS= read -r line
do
  SERVER=$(echo $line | cut -f1 -d":")
  MOUNT_POINT=$(echo $line | cut -f2 -d" ")

  # Check if server already tested
  if [[ " ${server_ok[*]} " == *" ${SERVER} "* ]]; then
    # The server is up, make sure the share are mounted
    net_mount $MOUNT_POINT
  elif [[ " ${server_notok[*]} " == *" ${SERVER} "* ]]; then
    # The server could not be reached, unmount the share
    net_umount $MOUNT_POINT
  else
    # Check if the server is reachable using ICMP
    ping -c 1 "${SERVER}" &>/dev/null

    # Check if the server is reachable using tcp
    # timeout 1 bash -c ": < /dev/tcp/${SERVER}/2049"

    if [ $? -ne 0 ]; then
      server_notok[${#server_notok[@]}]=$SERVER
      # The server could not be reached, unmount the share
      net_umount $MOUNT_POINT
    else
      server_ok[${#server_ok[@]}]=$SERVER
      # The server is up, make sure the share are mounted
      net_mount $MOUNT_POINT
    fi
  fi
done
