#!/usr/bin/env bash

# Alias which to 'command -v' if which does not exist
! which which > /dev/null 2>&1 && alias which='command -v'

if which hostname > /dev/null 2>&1; then
  hostname=$(hostname)
else
  hostname=$(hostnamectl hostname)
fi
hostname=${hostname%%.*}

which getent > /dev/null 2>&1
if [ $? != 0 ]; then
  getent() {
    cat /etc/passwd
    for dir in /Users/*; do
      [ ! -d $dir ] && continue
      id ${dir##*/} > /dev/null 2>&1 || continue
      user=${dir##*/}
      shell=$(dscl . -read /Users/$user UserShell | awk '{print $2}')
      name=$(dscl . -read /Users/$user RealName | paste -sd ' ' - | sed -E 's/^RealName: +//')
      echo "$user:*:$(id -u $user):$(id -g $user):$name:$dir:$shell"
    done
  }
fi

sum() {
  openssl dgst -sha256 | awk '{print $NF}'
}

unset add_dirs
if mount | grep -q " on /export/homes "; then
  add_dirs=/export/homes/*
fi
[ -d /etc/ssh/authorized_keys.d ] && add_dirs="$add_dirs /etc/ssh/authorized_keys.d/*"

default_key=$(echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOgO13IYDIa4H0ebwea5xFnEQpPutuKfpKkD7pz8Dhmo mike@erdelynet.com" | sum)
root_key=$(echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOgO13IYDIa4H0ebwea5xFnEQpPutuKfpKkD7pz8Dhmo mike@erdelynet.com
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEJwztKDEPYjFs0Z02V1zApEu6FuEGvKpqumbxODl5W9 root@earth
restrict,command="/srv/scripts/bin/rsync_ssh_client" ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJDsxNoLaDkuLIPH5293oREzILMYp0Q0ZBGxTzsCRHCu backup@earth' | sum)

declare -A keys def_keys checked

def_keys[/root/.ssh/authorized_keys]=$root_key
def_keys[/var/root/.ssh/authorized_keys]=$root_key

keys[mercury,/root/.ssh/authorized_keys.local]=$(
  echo 'restrict,command="rsync --server --sender -vlogDtpre.iLsfxCIvu . /var/lib/libvirt/images/" ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOJ7HDgDz7L8EJYQ2JYpv7eKdQfdlSZlNkD/xoGnAK8J backup2@earth' | sum
)
keys[sinope,/home/mike/.ssh/authorized_keys.local]=$(
  echo 'from="192.168.26.235",restrict,command="/srv/scripts/bin/picframe_mode.sh" ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPibUaqgOGK0ZyE5Fi7o3LfNu23J1/wDYUjy1f+CMmKQ homeassistant' | sum
)
keys[carpo,/home/ha/.ssh/authorized_keys]=$(
  echo 'from="192.168.25.40",command="$HOME/bin/manage_camera",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPibUaqgOGK0ZyE5Fi7o3LfNu23J1/wDYUjy1f+CMmKQ homeassistant' | sum
)
keys[venus,/var/root/.ssh/authorized_keys.local]=$(
  echo 'restrict,command="/opt/scripts/bin/rsync_ssh_client" ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJDsxNoLaDkuLIPH5293oREzILMYp0Q0ZBGxTzsCRHCu backup@earth' | sum
)

for hdir in $(getent passwd | awk -F: '{print $6}') $add_dirs; do
  for ak in $hdir/.ssh/authorized_keys $hdir/.ssh/authorized_keys2 $hdir/.ssh/authorized_keys.local; do
    [ "${checked[$ak]}" = true ] && continue
    keysum=$default_key
    [ -n "${def_keys[$ak]}" ] && keysum=${def_keys[$ak]}
    [ -n "${keys[$hostname,$ak]}" ] && keysum=${keys[$hostname,$ak]}
    if sudo test -f $ak; then
      dgst=$(openssl dgst -sha256 $ak | awk '{print $2}')
      if [ -n "$keysum" ] && [ "$dgst" = "$keysum" ]; then
        echo "$ak: OK"
      elif [ -n "$keysum" ] && [ "$dgst" != "$keysum" ]; then
        echo "$ak: ERROR - HAS BEEN MODIFIED ($dgst)"
      else
        echo "$ak: WARNING - Key exists and is untracked ($dgst)"
      fi
    fi
    checked[$ak]=true
  done
done
