#!/usr/bin/env bash

# Alias which to 'command -v' if which does not exist
! which which > /dev/null 2>&1 && alias which='command -v'

if which hostname > /dev/null 2>&1; then
  hostname=$(hostname)
else
  hostname=$(hostnamectl hostname)
fi
hostname=${hostname%%.*}

which getent > /dev/null 2>&1
if [ $? != 0 ]; then
  getent() {
    cat /etc/passwd
    for dir in /Users/*; do
      [ ! -d $dir ] && continue
      id ${dir##*/} > /dev/null 2>&1 || continue
      user=${dir##*/}
      shell=$(dscl . -read /Users/$user UserShell | awk '{print $2}')
      name=$(dscl . -read /Users/$user RealName | paste -sd ' ' - | sed -E 's/^RealName: +//')
      echo "$user:*:$(id -u $user):$(id -g $user):$name:$dir:$shell"
    done
  }
fi

unset add_dirs
if mount | grep -q " on /export/homes "; then
  add_dirs=/export/homes/*
fi
[ -d /etc/ssh/authorized_keys.d ] && add_dirs="$add_dirs /etc/ssh/authorized_keys.d/*"

default_key=$(echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOgO13IYDIa4H0ebwea5xFnEQpPutuKfpKkD7pz8Dhmo mike@erdelynet.com" | openssl dgst -sha256 | awk '{print $NF}')

declare -A keys def_keys checked

def_keys[/root/.ssh/authorized_keys]=777ab2f005173f3c0cd50677c257c604e99ea0a35cd50d44180a19780cd264cb  # mike + root@earth + rsync_ssh_client

keys[mercury,/root/.ssh/authorized_keys.local]=994d2c526213395f8e60aea7144ad6a16f25223498e82d5eeb8487df3861fdc8  # libvirt backup
keys[sinope,/home/mike/.ssh/authorized_keys.local]=e9cd01694fe8e5bd97700e185e5dfbd41af4d40883609b96f4aa41c795789459  # home assistant picframe
keys[carpo,/home/ha/.ssh/authorized_keys]=3c3606a749f96b37ca0b9c187983a2e823ff73dba75739b77c326402b8245ae6  # home assistant
keys[venus,/var/root/.ssh/authorized_keys.local]=a2990caf248c5642b577e1c815e59c491554a274333935d7fa6dfdedc84da973  # rsync_ssh_client in /opt/scripts/bin

for hdir in $(getent passwd | awk -F: '{print $6}') $add_dirs; do
  for ak in $hdir/.ssh/authorized_keys $hdir/.ssh/authorized_keys2 $hdir/.ssh/authorized_keys.local; do
    [ "${checked[$ak]}" = true ] && continue
    keysum=$default_key
    [ -n "${def_keys[$ak]}" ] && keysum=${def_keys[$ak]}
    [ -n "${keys[$hostname,$ak]}" ] && keysum=${keys[$hostname,$ak]}
    if sudo test -f $ak; then
      dgst=$(openssl dgst -sha256 $ak | awk '{print $2}')
      if [ -n "$keysum" ] && [ "$dgst" = "$keysum" ]; then
        echo "$ak: OK"
      elif [ -n "$keysum" ] && [ "$dgst" != "$keysum" ]; then
        echo "$ak: ERROR - HAS BEEN MODIFIED ($dgst)"
      else
        echo "$ak: WARNING - Key exists and is untracked ($dgst)"
      fi
    fi
    checked[$ak]=true
  done
done
